// app/layout.tsx or app/layout.js
import type { Metadata } from "next";
import { Lora } from "next/font/google";
import "./globals.css";

import Footer from "@/components/web/Footer";

import AuthProvider from "@/components/Provider/AuthProvider";
import Providers from "@/components/Provider/providers";
import Navbar from "@/components/web/Navbar/Navbar";
import { Toaster } from "sonner";
import { getDictionary } from "@/dictionaries/dictionaries";
import ConsoleWarning from "@/components/ConsoleWarning";

// Import Raleway font
const newFont = Lora({
  subsets: ["latin"],
  variable: "--font-raleway",
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Seul-Miraz",
  description: "Generated by create next app",
  icons:{
    icon:"/Design_sans_titre.svg"
  }
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: { lang: string };
}>) {
  const { lang } = params;
  const dict = await getDictionary(lang as "en" | "ar");
  
  return (
    <html lang="en" dir={lang === "ar" ? "rtl" : "ltr"} className={`${newFont.className} scroll-smooth`}>
      <body className={`${newFont.variable} antialiased`}>
        <Providers>
          <AuthProvider>
            <Navbar lang={lang} dict={dict} />
            <ConsoleWarning/>
            {children}
            <Toaster position="top-right" />
            <Footer dict={dict} lang={lang} />
          </AuthProvider>
        </Providers>
      </body>
    </html>
  );
}
